apiVersion: apps/v1
kind: Deployment
metadata:
  name: lebrickbot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lebrickbot-frontend
  template:
    metadata:
      labels:
        app: lebrickbot-frontend
    spec:
      containers:
        - name: frontend
          image: lebrickbot-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
