{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openluffy.fullname" . }}-postgres
  labels:
    {{- include "openluffy.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "openluffy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
