apiVersion: apps/v1
kind: Deployment
metadata:
  name: lebrickbot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lebrickbot-backend
  template:
    metadata:
      labels:
        app: lebrickbot-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.backend }}
          ports:
            - containerPort: 8000
          env:
            - name: AWS_ROLE_ARN
              value: {{ .Values.aws.roleArn | quote }}
