apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lebrickbot
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: lebrickbot-strip-api@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: openbrick.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: lebrickbot-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lebrickbot-frontend
                port:
                  number: 80
